
---
title: "magrittr/dplyr demo"
author: "Andrew and Kieran"
date: "May 5, 2015"
output: 
  html_document:
      keep_md: yes
---

### Part 1: magrittr basics
install.packages("magrittr")
install.packages("gapminder")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("visreg")

```{r}
# load libraries
library("magrittr")
library("gapminder")
library("dplyr")
library("ggplot2")
library("visreg")

# recall function rnorm
rnorm(n = 100, mean = 0)

# basic pipe usage
# output of pipe is (by default) passed to *first* argument of target function
rnorm(100) %>% mean
rnorm(100) %>% hist

#this includes when arguments other than the first are explicitly defined, e.g.
100 %>% rnorm(mean = 10) %>% hist

# can pipe to as many functions as you like
100 %>% rnorm %>% mean
100 %>% rnorm %>% abs %>% sqrt %>% mean

#compare to parenthesis mess below
mean(sqrt(abs(rnorm(100))))

#another example
letters %>% toupper %>% rev %>% paste0 (collapse = "") 

# what if we want to pipe in places other than the first argument?
# use "."
10 %>% rnorm(n = 100, mean = .) %>% mean

# pipe a dataframe to subset 
gapminder %>% subset(country == "Zambia") 

# what will this do?
gapminder %>% lapply(class)

# pipin hot linear models
gapminder %>% lm(lifeExp ~ gdpPercap, data = .)
gapminder %>% lm(lifeExp ~ gdpPercap, data = .) %>% summary
gapminder %>% lm(lifeExp ~ gdpPercap, data = .) %>% anova
gapminder %>% lm(lifeExp ~ gdpPercap + continent + country + pop, data=.) %>% drop1

# we can also assign the output of a pipe like so:
gm.mod <- gapminder %>% lm(lifeExp ~ log(gdpPercap), data = .)
visreg(gm.mod)

```

### Part 2: magrittr extended

```{r}

# define "functional sequences""
funct <- . %>% abs %>% sqrt %>% hist
rnorm(100) %>% funct

# same as
f <- function(x){
  hist(sqrt(abs(x)))
}

# what if we need to make each "step" a bit more complex? 
# could define a function outside, but can also do it "in line"
# i.e. lambda expressions

 rnorm(100) %>% 
  abs() %>% {
  x <- sqrt(.)
  y <- exp(.)
  x * y
  } %>%
  hist

# pass arbitrary numbers of args 
list(x = rnorm(100), y = runif(100)) %>% with(cor(x, y))

# short form is the %$% ("exposition"") operator
list(x = rnorm(100), y = runif(100)) %$% cor(x, y)

# what if we want to pipe through a function with no return value (e.g. a plot?), but continue the pipe?
# can use the "tee" operator %T>%
# creates a "branch" in the pipe

rnorm(100) %>%
  abs %T>%
  hist %>%
  log

list(x = rnorm(100), y = rnorm(100)) %T>% 
  with(plot(x, y)) %>%
  with(lm(y ~ x)) %T>% 
  abline %>% 
  summary

plot.model <- . %T>% 
  with(plot(x, y)) %>%
  with(lm(y ~ x)) %T>% 
  abline %>% 
  summary

list(x = rnorm(100), y = rnorm(100)) %>% plot.model

```

### Part 3: dplyr basics

```{r}

# create a data frame tbl (not usually necessary)
gm <- gapminder %>% tbl_df 

# tbl_dfs can be easily converted back to datafames
gm %>% data.frame() %>% head()

# arrage dataframe by a variable
gm %>% arrange(year)

# select columns of a dataframe
gm %>% select(year, country, continent)

# create a new column 
gm %>% mutate(pop.thou = pop/1000)
gm %>% mutate(pop.thou = pop/1000, pop.mil = pop/1000000)

# filter rows by some criteria
gm %>% filter(country == "Zambia")
gm %>% filter(country == "Zambia", year < 1977)

# create a grouped tbl_df ("grouped_df")
gm %>% 
  group_by(country)

# apply a function to the groups (e.g. summarise)
gm %>% 
  group_by(country) %>%
  summarize(mean_life = mean(lifeExp))

# multiple groups can be specified
gm %>% 
  group_by(continent, country) 

# functions are applied from last to first specified
gm %>% 
  group_by(continent, country) %>%
  summarize(mean_life = mean(lifeExp)) 

# after the last function is applied, a tbl_df (no groups) is returned
gm %>% 
  group_by(continent, country) %>%
  summarize(mean_life = mean(lifeExp)) %>%
  summarize(mean_contient_life = mean(mean_life))

# tally: count observations in groups
gm %>% 
  group_by(continent, country) %>%
  tally %>%
  tally

# example of a complete chain
library(ggplot2)

gm %>% 
  group_by(continent, year) %>%
  summarize(meanlife = mean(lifeExp)) %>%
  ggplot(aes(x = year, y = meanlife, colour = continent)) + 
    geom_point() + 
    geom_line()

```

### Part 4: dplyr extended

```{r}

# insert join stuff here


# identify outliers of some kind?



```



